# Generated by Django 5.2 on 2025-04-21 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id_clinica', models.AutoField(primary_key=True, serialize=False)),
                ('cnpj', models.CharField(max_length=45)),
                ('nome', models.CharField(max_length=45)),
                ('numero', models.CharField(max_length=45)),
                ('Endereco', models.CharField(max_length=45)),
                ('senha', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'clinica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.DateTimeField()),
                ('inicio', models.TimeField()),
                ('fim', models.TimeField()),
            ],
            options={
                'db_table': 'horarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id_pessoa', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=45)),
                ('data_nascimento', models.DateField()),
                ('nome', models.CharField(max_length=45)),
                ('senha', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=45)),
                ('type', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'db_table': 'pessoa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id_pessoa', models.OneToOneField(db_column='id_pessoa', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='agendamento.pessoa')),
                ('crm', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'medico',
                'managed': False,
            },
        ),
    ]
