# Generated by Django 5.2 on 2025-04-24 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='id_pessoa', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='agendamento.pessoa')),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('endereco', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
